### ISSUE TITLE
On Turing incompleteness of  NISP

### ISSUE THREAD

**Issue by kannangce** [ysmood/nisp#15]
I would like to understand more about the of "Turing Incompleteness" of NISP.

- What precisely makes NISP turing incomplete? Is it the absense of states/variables?
- What is the advantage that we gain with this(Turing incompleteness) nature?

**PS:** It would be great if some of them are added to the wiki of the library as well.

**Comment by ysmood** [comment]
> What precisely makes NISP turing incomplete? Is it the absense of states/variables?

Yes, it means the absence of all the primitives, not just states or variables.

> What is the advantage that we gain with this(Turing incompleteness) nature?

You normally can't expose SQL to public users, because it's Turing Complete, the user can attack the system easily by composing an infinite for-loop.
For example, we can use nisp to expose some components of SQL, such as `where`, `<`, `>`, `&&`, `||`, "==", `limit`, etc, so that users can compose whatever query they like and we don't have to spend a lot of time to create each CRUD API they need. No matter how the attacker composes the statements, they can't attack the DB.

Such as query users that are level 3 and age between 20 and 30, then only return their names. It will be hard to do it in RESTful API, you normally will have to send several requests to complete it, and if the user object is huge, you have to waste a lot of bandwidth. But with nisp only one request is enough, the query might look like this:

```
(map
    (query 'users'
        (&&
            (||
                (> 'age' 20)
                (< 'age' 30)
            )
            (== 'level' 3)
        )
    )
    
    (fn user (get user 'name'))
)
```

I think nisp is much more powerful than things like GraphQL. If the community can create tools for it, it will be even easier to learn and use than GraphQL.

**Comment by ysmood** [comment]
> PS: It would be great if some of them are added to the wiki of the library as well.

You are welcome to make a PR to help me doc it.

**Comment by kannangce** [comment]
On the below statement,
> Yes, it means the absence of all the primitives, not just states or variables.

wrt, primitives, we don't have any constraints on defining any primitives. With functions and macros, we can define any primitive such as conditionals and looping as we want. I guess the only thing missing is variables. Isn't it?

**Comment by kannangce** [comment]
> You are welcome to make a PR to help me doc it.

Sure! I'm developing a similar [lib](https://github.com/kannangce/j-s-exp) for Java. It's pretty much WIP now.

**Comment by ysmood** [comment]
> I guess the only thing missing is variables. Isn't it?

No, you can define a way to let users use memory. Actually we have examples in the unit tests to show how to do it:

https://github.com/ysmood/nisp/blob/62964e7058fa6d1ea6c6424920f8327acda75924/test/basic.ts#L209-L219

Nisp is empty by default, but you can make it Turing Complete by adding primitives to it. Here's one of my favorite words:

> The Usefulness of the Cup is its emptiness. - Bruce Lee

**Comment by ysmood** [comment]
> I'm developing a similar lib for Java. It's pretty much WIP now.

Once your project is usable, it will be great if you can make a PR to link them together, after the ruby and golang version:

https://github.com/ysmood/nisp#implementaions

**Comment by kannangce** [comment]
> > I'm developing a similar lib for Java. It's pretty much WIP now.
> 
> Once your project is usable, it will be great if you can make a PR to link them together, after the ruby and golang version:
> 
> https://github.com/ysmood/nisp#implementaions

Sure!
Will be doing it anyway. Co-referenced implementations of this makes it more suitable for inter-operability of expressions across languages, when needed.
